version: '2'
services:

  database:
      container_name: database-container
      image: mysql:5.6
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=password1
        - MYSQL_DATABASE=comments
      ports:
        - "3306:3306"